import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#E5E5E5',
    paddingTop: 16,
  },
  containerOnForms: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E5E5E5',
    paddingBottom: 120,
  },
  optionsWrapper: {
    width: '80%',
    height: '30%',
    borderRadius: 25,
    backgroundColor: '#03113c',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
  },
  excludeButtonStatic: {
    width: '100%',
    height: '45%',
    borderWidth: 1,
    borderRadius: 50,
    borderColor: 'red',
    justifyContent: 'center',
  },
  excludeButtonPressed: {
    width: '100%',
    height: '45%',
    borderRadius: 50,
    justifyContent: 'center',
    backgroundColor: 'red',
  },
  formWrapper: {
    width: '80%',
    borderRadius: 25,
    backgroundColor: '#03113c',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingVertical: 24,
  },
  formWrapperForChangePassword: {
    width: '80%',
    borderRadius: 25,
    backgroundColor: '#03113c',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingBottom: 24,
  },
  goBackButtonStatic: {
    width: '40%',
    height: 40,
    borderWidth: 1,
    borderRadius: 40,
    borderColor: 'gray',
    justifyContent: 'center',
    alignItems: 'center',
  },
  goBackButtonPressed: {
    width: '40%',
    height: 40,
    borderRadius: 40,
    backgroundColor: 'gray',
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveChangesButtonStatic: {
    width: '40%',
    height: 40,
    borderWidth: 1,
    borderRadius: 40,
    borderColor: 'green',
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveChangesButtonPressed: {
    width: '40%',
    height: 40,
    borderRadius: 40,
    backgroundColor: 'green',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
